### ISSUE TITLE
Add handler to update menu

### ISSUE THREAD

**Issue by reidmweber** [mhink/react-ionize#1]
I'm wondering how you'd do something like have a menu item with a different label depending on the state. For example, "Enter Fullscreen" and "Exit Fullscreen". 
I haven't seen a straightforward way to re-render or update the menu on state changes like this.

**Comment by mhink** [comment]
Kudos- credit for first bug report goes to you, haha. I went to write a demo for how to do this, and realized it wasn't working. Turns out I tested *adding and removing* menu items dynamically, but not actually *changing* an existing one. Whoops. The fix is in #0410ec2.

As to your question, I've added /examples/dynamic-menu.js to demonstrate how you'd go about updating a <menuitem /> in response to a state change.
